
/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/
#include "can_messages_tx.h"
#include <stdbool.h>

#include "u_tx_debug.h"
#include "u_queues.h"
#include "c_utils.h"
#include "fdcan.h"
#include "bitstream.h"


static void handle_bitstream_overflow(bitstream_t *bitstream_res,
					    uint32_t can_id);

uint8_t send_lightning_board_imu_acceleration_data
(float accel_x,float accel_y,float accel_z)
{
    can_msg_t msg;
    msg.id = 0xAAA;
    msg.id_is_extended = true;msg.len = 6;

    
            uint64_t data = 0;
                        int32_t accel_x_i = (int32_t)(accel_x*1000);
                        if(accel_x_i > 32767) {accel_x_i = 32767;
                        } else if(accel_x_i < -32768) {accel_x_i = -32768;
                        }
                        data |= ((uint32_t)(accel_x_i) & 0xFFFFULL) << 48;
            
                        int32_t accel_y_i = (int32_t)(accel_y*1000);
                        if(accel_y_i > 32767) {accel_y_i = 32767;
                        } else if(accel_y_i < -32768) {accel_y_i = -32768;
                        }
                        data |= ((uint32_t)(accel_y_i) & 0xFFFFULL) << 32;
            
                        int32_t accel_z_i = (int32_t)(accel_z*1000);
                        if(accel_z_i > 32767) {accel_z_i = 32767;
                        } else if(accel_z_i < -32768) {accel_z_i = -32768;
                        }
                        data |= ((uint32_t)(accel_z_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_lightning_board_imu_gyro_data
(float gyro_x,float gyro_y,float gyro_z)
{
    can_msg_t msg;
    msg.id = 0xAAB;
    msg.id_is_extended = true;msg.len = 6;

    
            uint64_t data = 0;
                        int32_t gyro_x_i = (int32_t)(gyro_x*1000);
                        if(gyro_x_i > 32767) {gyro_x_i = 32767;
                        } else if(gyro_x_i < -32768) {gyro_x_i = -32768;
                        }
                        data |= ((uint32_t)(gyro_x_i) & 0xFFFFULL) << 48;
            
                        int32_t gyro_y_i = (int32_t)(gyro_y*1000);
                        if(gyro_y_i > 32767) {gyro_y_i = 32767;
                        } else if(gyro_y_i < -32768) {gyro_y_i = -32768;
                        }
                        data |= ((uint32_t)(gyro_y_i) & 0xFFFFULL) << 32;
            
                        int32_t gyro_z_i = (int32_t)(gyro_z*1000);
                        if(gyro_z_i > 32767) {gyro_z_i = 32767;
                        } else if(gyro_z_i < -32768) {gyro_z_i = -32768;
                        }
                        data |= ((uint32_t)(gyro_z_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_lightning_board_lightning_sensor_information
(uint8_t interrupt,uint8_t distance,uint32_t energy)
{
    can_msg_t msg;
    msg.id = 0xAAC;
    msg.id_is_extended = true;msg.len = 6;

    
            uint64_t data = 0;
                        uint32_t interrupt_i = (uint32_t)(interrupt);
                        if(interrupt_i > 255ULL) {interrupt_i = 255;
                        }
                        data |= ((interrupt_i) & 0xFFULL) << 56;
            
                        uint32_t distance_i = (uint32_t)(distance);
                        if(distance_i > 255ULL) {distance_i = 255;
                        }
                        data |= ((distance_i) & 0xFFULL) << 48;
            
                        uint32_t energy_i = (uint32_t)(energy);
                        if(energy_i > 4294967295ULL) {energy_i = 4294967295;
                        }
                        data |= ((energy_i) & 0xFFFFFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_lightning_board_magnometer_sensor_information
(float mag_x,float mag_y,float mag_z)
{
    can_msg_t msg;
    msg.id = 0xAAD;
    msg.id_is_extended = true;msg.len = 6;

    
            uint64_t data = 0;
                        int32_t mag_x_i = (int32_t)(mag_x*1000);
                        if(mag_x_i > 32767) {mag_x_i = 32767;
                        } else if(mag_x_i < -32768) {mag_x_i = -32768;
                        }
                        data |= ((uint32_t)(mag_x_i) & 0xFFFFULL) << 48;
            
                        int32_t mag_y_i = (int32_t)(mag_y*1000);
                        if(mag_y_i > 32767) {mag_y_i = 32767;
                        } else if(mag_y_i < -32768) {mag_y_i = -32768;
                        }
                        data |= ((uint32_t)(mag_y_i) & 0xFFFFULL) << 32;
            
                        int32_t mag_z_i = (int32_t)(mag_z*1000);
                        if(mag_z_i > 32767) {mag_z_i = 32767;
                        } else if(mag_z_i < -32768) {mag_z_i = -32768;
                        }
                        data |= ((uint32_t)(mag_z_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}



/// @brief A helper which sends appropriate error to stdout and CAN if a bistream overflows
/// @param bitstream_res The bitstream to check for overflow
/// @param can_id The CAN ID this bistream data is intended for
/// @return 0 if success
static void handle_bitstream_overflow(bitstream_t *bitstream_res,
					    uint32_t can_id)
{
	if (!bitstream_res->overflow) {
		return;
	}

    
}