#ifndef _CAN_MSGS_TX_H
#define _CAN_MSGS_TX_H

/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/
#include <stdbool.h>
#include <stdint.h>

/**
* Contents of this message:
* Lightning/IMU/Acceleration - Lightning Board IMU Acceleration Data.
*/
uint8_t send_lightning_board_imu_acceleration_data
(float accel_x,float accel_y,float accel_z);

/**
* Contents of this message:
* Lightning/IMU/Gyro - Lightning Board IMU Gyroscope Data.
*/
uint8_t send_lightning_board_imu_gyro_data
(float gyro_x,float gyro_y,float gyro_z);

/**
* Contents of this message:
* Lightning/LightningSensor/Data - Lightning Board Lightning Sensor Information.
*/
uint8_t send_lightning_board_lightning_sensor_information
(uint8_t interrupt,uint8_t distance,uint32_t energy);

/**
* Contents of this message:
* Lightning/Magnometer/Data - Lightning Board Magnometer Sensor Information.
*/
uint8_t send_lightning_board_magnometer_sensor_information
(float mag_x,float mag_y,float mag_z);
#endif